# COGS 108 - Data Checkpoint

# Research Question

What is the impact of engaging in at least 150 minutes per day of physical activity on GPA among college school students aged 18-24, and how do factors such as hours socialized, extracurriculars, and time spent studying influence academic performance individually, as well as in conjunction with one another?

## Background and Prior Work


Years of evidence and research suggests that maintaining a consistent exercise routine leads to improved performance in the classroom. A number of studies around the world have found that, especially in children, exercise and overall fitness coupled with other lifestyle factors such as physical activity, balanced study time, sleep, and social interaction can be linked to academic performance. In the UK, a study by Hill et al. (2011) measured the academic improvement of primary school children who participated in daily exercise compared to those who did not, revealing significant gains in the children who exercised. Similarly, in Korea, Shin et al. (2021) found a positive association between the amount of physical activity and test scores among middle school students.

For this project, this analysis extends that idea to college students by examining how consistent physical activity may impact academic performance. To further build on this idea, the project also explores whether other factors such as study time and social interaction combined with exercise may optimize a student's ability to succeed. Universities foster an environment of extremely high academic rigor and expectation, making it valuable to examine whether exercise influences academic outcomes among college students. While exercise is already known to improve general health and lifestyle, this project investigates whether different daily activities can complement exercise and how these factors together may affect academic success. In a recent study, Martinez (2020) found that 80% of adolescents do not exercise enough, while Li et al. (2024) reported a major lack of exercise commitment and consistency among college students. If any relationship exists between exercise and academic success, these findings could encourage college students to prioritize physical activity despite busy schedules.


**References:**
1. https://doi.org/10.1111/j.1469-8749.2011.03954.x
2. https://mdpi-res.com/mathematics/mathematics-09-03105/article_deploy/mathematics-09-03105.pdf?version=1638425203
3. https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(20)31859-6/fulltext
4. https://www.sciencedirect.com/science/article/pii/S0001691824001306?via%3Dihub

# Hypothesis


Engaging in at least 150 minutes per day of physical activity will positively impact GPA among college students aged 18-24. Additionally, students who maintain above 8 hours of sleep, engage in daily socializing, and participate in extracurricular activities will experience greater improvements in academic performance than those without these consistent habits.

# Student Lifestyle Dataset

## Data Overview

Link to dataset: https://www.kaggle.com/datasets/steve1215rogg/student-lifestyle-dataset/data

Number of Observations: 2000

Number of Variables: 8

The Student Lifestyle Dataset includes variables related to physical activity, academic performance, and lifestyle habits among college students. These variables provide insights into students' health and study habits, with physical activity and sleep likely serving as proxies for overall well-being and energy levels, while study hours directly relate to academic effort. The combination of these factors can give a holistic view of the lifestyle elements that might impact academic performance.

### Important Variables
The Student Lifestyle Dataset has 8 variables being measured.

- Student_ID - This is the "given" student id for each student that filled out the survey. (Same as the Index, int)

- Study_Hours_Per_Day - This is the average amount of hours a student spends studying for their classes a day in an academic school year. (float)
- Extracurricular_Hours_Per_Day - This is the average amount of hours a student spends doing extracurricular activites a day in an academic school year. (float)
- Sleep_Hours_Per_Day - This is the average amount of hours a student spends sleeping a day in an academic school year. (float)
- Social_Hours_Per_Day -  This is the average amount of hours a student spends socializing a day in an academic school year. (float)
- Physical_Activity_Hours_Per_Day - This is the average amount of hours a student spends doing physical activites or exercising a day in an academic school year. (float)
- GPA -  This is the average GPA for each student in the given academic school year. (float)
- Stress_Level - Stress level has can take three values: Low, Moderate, or High (str)

### Wrangling and Cleaning Process
The dataset would first be cleaned by renaming the columns to create clearer and more organized variable names. The next step would be checking whether the values in each column are reasonable. For example, the Study, Extracurricular, Sleep, Social, and Physical Hours columns should contain only positive values because an activity cannot be performed for a negative amount of time. Values greater than 24 would also be checked since an activity cannot exceed the total number of hours in a day. The Stress_Level column would then be converted into integer values to make regressions and comparisons between variables easier to perform. This would be done by assigning numerical values to each category: Low = 1, Moderate = 2, and High = 3. Finally, the Student_ID column could be removed because it contains the same information as the Index column and would not add any additional value to the analysis.

In [ ]:
#Import packages

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import datetime

In [ ]:
df = pd.read_csv('student_lifestyle_dataset.csv')
df

,Student_ID,Study_Hours_Per_Day,Extracurricular_Hours_Per_Day,Sleep_Hours_Per_Day,Social_Hours_Per_Day,Physical_Activity_Hours_Per_Day,GPA,Stress_Level
0,1,6.9,3.8,8.7,2.8,1.8,2.99,Moderate
1,2,5.3,3.5,8.0,4.2,3.0,2.75,Low
2,3,5.1,3.9,9.2,1.2,4.6,2.67,Low
3,4,6.5,2.1,7.2,1.7,6.5,2.88,Moderate
4,5,8.1,0.6,6.5,2.2,6.6,3.51,High
...,...,...,...,...,...,...,...,...
1995,1996,6.5,0.2,7.4,2.1,7.8,3.32,Moderate
1996,1997,6.3,2.8,8.8,1.5,4.6,2.65,Moderate
1997,1998,6.2,0.0,6.2,0.8,10.8,3.14,Moderate
1998,1999,8.1,0.7,7.6,3.5,4.1,3.04,High
1999,2000,9.0,1.7,7.3,3.1,2.9,3.58,High

In [ ]:
#New Column Names
df.columns = ['Student ID', 'Study', 'Extracurricular', 'Sleep', 'Social', 'Physical Activity', 'GPA', 'Stress Level']
df

,Student ID,Study,Extracurricular,Sleep,Social,Physical Activity,GPA,Stress Level
0,1,6.9,3.8,8.7,2.8,1.8,2.99,Moderate
1,2,5.3,3.5,8.0,4.2,3.0,2.75,Low
2,3,5.1,3.9,9.2,1.2,4.6,2.67,Low
3,4,6.5,2.1,7.2,1.7,6.5,2.88,Moderate
4,5,8.1,0.6,6.5,2.2,6.6,3.51,High
...,...,...,...,...,...,...,...,...
1995,1996,6.5,0.2,7.4,2.1,7.8,3.32,Moderate
1996,1997,6.3,2.8,8.8,1.5,4.6,2.65,Moderate
1997,1998,6.2,0.0,6.2,0.8,10.8,3.14,Moderate
1998,1999,8.1,0.7,7.6,3.5,4.1,3.04,High
1999,2000,9.0,1.7,7.3,3.1,2.9,3.58,High

In [ ]:
#Change Stress Level Column to be Integers
def stress_level(level):
    if level == 'Low':
        return 1
    elif level == 'Moderate':
        return 2
    elif level == 'High':
        return 3

df['Stress Level'] = df['Stress Level'].apply(stress_level)
df

,Student ID,Study,Extracurricular,Sleep,Social,Physical Activity,GPA,Stress Level
0,1,6.9,3.8,8.7,2.8,1.8,2.99,2
1,2,5.3,3.5,8.0,4.2,3.0,2.75,1
2,3,5.1,3.9,9.2,1.2,4.6,2.67,1
3,4,6.5,2.1,7.2,1.7,6.5,2.88,2
4,5,8.1,0.6,6.5,2.2,6.6,3.51,3
...,...,...,...,...,...,...,...,...
1995,1996,6.5,0.2,7.4,2.1,7.8,3.32,2
1996,1997,6.3,2.8,8.8,1.5,4.6,2.65,2
1997,1998,6.2,0.0,6.2,0.8,10.8,3.14,2
1998,1999,8.1,0.7,7.6,3.5,4.1,3.04,3
1999,2000,9.0,1.7,7.3,3.1,2.9,3.58,3

In [ ]:
#Drop Student ID Column
df = df.drop('Student ID', axis=1)
df

,Study,Extracurricular,Sleep,Social,Physical Activity,GPA,Stress Level
0,6.9,3.8,8.7,2.8,1.8,2.99,2
1,5.3,3.5,8.0,4.2,3.0,2.75,1
2,5.1,3.9,9.2,1.2,4.6,2.67,1
3,6.5,2.1,7.2,1.7,6.5,2.88,2
4,8.1,0.6,6.5,2.2,6.6,3.51,3
...,...,...,...,...,...,...,...
1995,6.5,0.2,7.4,2.1,7.8,3.32,2
1996,6.3,2.8,8.8,1.5,4.6,2.65,2
1997,6.2,0.0,6.2,0.8,10.8,3.14,2
1998,8.1,0.7,7.6,3.5,4.1,3.04,3
1999,9.0,1.7,7.3,3.1,2.9,3.58,3

In [ ]:
#Check Values in Columns are Positive
only_positive_cols = 7
for col in df.columns:
    if (df[col] >= 0).all() == 0:
        only_positive_cols -= 1

print('All Values in Columns are Positive: ' + str(only_positive_cols == len(df.columns)))

#Check Values in Columns are less than 24
less_than_24_cols = 7
for col in df.columns:
    if (df[col] <= 24).all() == 0:
        less_than_24_cols -= 1

print('All Values in Columns are Less than 24: ' + str(less_than_24_cols == len(df.columns)))

All Values in Columns are Positive: True
All Values in Columns are Less than 24: True

# Ethics & Privacy

When exploring the relationship between lifestyle factors such as exercise, study time, sleep, and social interactions and their effect on GPA among college students, ethical considerations and privacy concerns are important to ensure participant information is protected and the analysis remains objective. Privacy is especially important because the data may contain sensitive information related to academic performance, exercise habits, and demographic characteristics. To address these concerns, only data directly relevant to the research question would be used, with a focus on broader demographic categories rather than highly specific personal information. Additionally, each dataset’s terms of use would be reviewed to ensure proper use and compliance with data guidelines.

Potential sources of bias are also important to consider. The datasets may contain sampling biases, such as an overrepresentation of students who exercise regularly or limited diversity across demographic factors such as age, gender, or major. These biases could affect how broadly the findings apply to larger populations. To identify and reduce these issues, findings would be compared across multiple datasets when possible. This approach can strengthen the results and help reveal biases that may exist within a specific data source. Demographic characteristics within the sample would also be monitored throughout the analysis. Any notable limitations, biases, or lack of diversity would be clearly reported so the findings can be interpreted more accurately. Taking these steps helps maintain an ethical and balanced analysis.